Swiftlint rules in color templates
SwiftGen/templates pull request #32
Opened 2017-04-04 06:31 UTC by evil159

There was inconsistency in `swiftlint` rules: `file_length`, and `line_length` were disabled but not enabled back(probably not a big deal, just a minor thing). 
Another thing was that vertical alignment of variables inside `Color` extension initialiser caused `swiftlint` to emit a warning based on `operator_usage_whitespace ` rule, fixed it by disabling this rule for the `Color` extension.

2017-04-04 07:46 UTC, djbe commented
Hi,

Thank you for the contribution!

A quick tip for those failing tests: you can run them locally using either the xcode project (use the CMD + U shortcut), or in terminal using `rake xcode:test`.
Also, please add a changelog entry, using the same formatting as the other entries.

2017-04-04 17:43 UTC, evil159 commented
Thanks for the tip 👍🏻

2017-04-04 17:56 UTC, djbe commented on CHANGELOG.md
> +* Fixed `swiftlint` warnings in generated color extensions
Please use the same format as the other entries:
- credit yourself
- add a link to this PR
- a `.` at the end of the sentence and 2 spaces

2017-04-04 17:58 UTC, djbe requested changes
Please fix the changelog entry format. Other than that, this LGTM.

2017-04-04 22:54 UTC, djbe commented on CHANGELOG.md
> +[Roman Laitarenko](https://github.com/evil159)
Hate to be nitpicky here, but please indent the username and PR links.

2017-04-05 10:57 UTC, djbe approved these changes

2017-04-05 13:19 UTC, merged