Workaround to fix classname issues with storyboards and customModule
SwiftGen/templates pull request #36
Opened 2017-04-15 15:32 UTC by juli1quere

Hey, 

Here is the workaround to fix classname issues with storyboards and customModule (as described in #25) :)

2017-04-16 23:05 UTC, djbe requested changes
Please implement this for all storyboard templates, not just the iOS swift3 version.

2017-04-16 23:05 UTC, djbe commented on templates/storyboards-swift3.stencil
> +
Also, no need to add this newline.

2017-04-17 11:19 UTC, juli1quere commented
Indeed, I forgot the other templates (sorry). Just updated the PR :)

2017-05-02 23:10 UTC, djbe submitted a review, later dismissed
Right, so this branch was quite out of date. With the merge, tests are running correctly now.
I noticed an error in the if test when matching `param.module`, it isn't testing the correct property.

Once #2 lands, this PR needs to add the needed documentation for the `ignoreTargetModule` parameter.

I'm wondering if we should add tests for this. @AliSoftware thoughts?

2017-05-02 23:10 UTC, djbe commented on templates/storyboards-default.stencil
> +{% macro className scene %}{% if scene.customClass %}{% if scene.customModule %}{% if not param.ignoreTargetModule or scene.customModule != env.PRODUCT_MODULE_NAME and scene != param.module %}{{scene
`scene != param.module`
should be
`scene.customModule != param.module`

2017-05-17 10:17 UTC, AliSoftware commented
Yeah, we totally should test this, specially given how it seems to be some strange behaviour of Xcode with storyboards which might change again in future Xcode version!

2017-06-12 21:21 UTC, ldiqual commented
@juli1quere Bump

2017-06-14 10:22 UTC, juli1quere commented
In fact, I do not have enough knowledge of Swiftgen to write tests that check this issue :/

2017-06-14 10:25 UTC, djbe commented
I'll write some tests if I can find some time this week, no promises though, might be next week.

2017-08-13 19:12 UTC, AliSoftware commented
Is this still relevant with the new SwiftGen 5.0 templates? If so, could we finish this PR to include it in the next release?

2017-08-13 19:20 UTC, djbe commented
The current templates will always prepend the module to scene classes, even for the target module. In some scenarios, the user might want to disable this, hence this PR.

2017-08-17 00:18 UTC, djbe commented
Hmmm, that's annoying... It can't compile our ignore target module files, because it can't find the custom class. The custom class is in an external module, and the import is ignored...

@AliSoftware thoughts? Add something to the filename that says "don't compile this"?

2017-08-17 07:02 UTC, AliSoftware commented
Can't we create a stub-env doing the import or something?

2017-08-17 10:34 UTC, djbe commented
The thing is, the best way to do this is if we could define the name of the `current` module when checking/compiling the code. At the time, I searched for a bit but didn't really find out how to, any help there would be useful.

If we can define a module when compiling both the output code + the definitions, I think we'll be able to solve this issue by adding the missing class to definitions.swift so that it's both in the "current" module and an imported one.

2017-08-17 12:26 UTC, djbe commented
Allright, @AliSoftware no idea what you'll think of this solution, but it works 😄

2017-08-17 19:48 UTC, AliSoftware commented
I think at that point basing the decision on the file name is acceptable. But in the long run I hope we won't have more exception and cases to consider.

Otherwise we might need to make our build tests evolve e.g. use a YAML or JSON file to describe the matrix of additional options needed for each template or whatnot. But for now let's go with name matching.

2017-09-07 04:08 UTC, ldiqual commented
@djbe Is this ready to go? I see that you removed the WIP label but didn't notify the maintainers.

2017-09-07 09:35 UTC, djbe commented
Eh, I left it open in case there was more feedback incoming. I suppose this can get merged 👍

2017-09-07 09:58 UTC, merged

2017-10-11 04:31 UTC, ldiqual commented
@AliSoftware Sorry to bother you on this PR, but I was wondering if you had an idea of when this fix will get released?

2017-10-11 04:44 UTC, AliSoftware commented
Should be included within the next version of SwiftGen next weekend