Improve swiftlint rules
SwiftGen/templates pull request #46
Opened 2017-05-09 11:56 UTC by djbe

Continuation of #35

Currently, the latest `swiftlint` version has a few issues with our output files. While we're at it, we might as well review the disable/enable rules we're using in the templates.

- Disable `file_length` for the whole file
- Disable `identifier_name` for generated identifiers (all swift versions, they can still be too short or long in swift 3)
- Disable `type_body_length` for generated types
- Disable `line_length` for generated lines
- Disable `nesting` for generated deep types (dot syntax)
- Disable `type_name` for generated deep types (dot syntax)
- Enable all disabled rules directly after the generated bits
- Remove `valid_docs` as it doesn't exist anymore and has been opt-in for a while
- Remove `variable_name` as it's been replaced by `identifier_name`

2017-05-09 16:12 UTC, djbe commented
While testing, I noticed (with `--enable-all-rules`) that we might want to disable these rules:
- `explicit_type_interface`: Getting this pretty much everywhere, maybe disable it like `file_length`
- `sorted_imports`: Getting this for a few templates. Might be hard to get the sorting right for templates that have extra module imports.

2017-05-10 18:37 UTC, AliSoftware commented
:+1: for disabling the `explicit_type_interface`.
For the `sorted_imports` rule what we _could_ do is make our static (hard-coded) imports sorted, and only add `// swiftlint:disable sorted_import` it if there are custom modules… but even that might be tricky too (we can't just `{% if modules %}` as we would need to remove `env.PRODUCT_MODULE_NAME` and `param.module` from that array first…) so probably not worth it and not so problematic to disable the rule every time then.

I also see that you took this opportunity to also move some `{% if colors %}` and similar up, so that it won't generate the static code parts either 👍

2017-05-10 18:41 UTC, AliSoftware requested changes
I haven't reviewed _every_ single rule changes you did on _all_ the templates(†), but in the meantime, I just discovered that we can disable multiple rules at once in a single comment, maybe that would avoid too much noise?

https://github.com/realm/SwiftLint#disable-rules-in-code

```swift
// swiftlint:disable <rule1> [<rule2> <rule3>...]
```

(†) [or said otherwise…](https://cdn.meme.am/cache/instances/folder42/500x/76872042/rent-is-too-damn-high-the-number-of-templates-expected-files-to-review-is-too-damn-high.jpg)

2017-05-10 18:41 UTC, AliSoftware commented on rakelib/lint.rake
> +    url = 'https://github.com/realm/SwiftLint/releases/download/0.18.1/SwiftLint.pkg'
👍

2017-05-10 19:13 UTC, djbe commented
Allright, I'll see about those extra rules, and putting them in 1 comment where possible.

Luckily, you only need to review the templates, not the output code (which I'm doing manually for now 😅 )

2017-05-10 19:32 UTC, Liquidsoul commented on Tests/Expected/Storyboards-iOS/default-context-all-customname.swift
> +// swiftlint:disable sorted_imports
Why not just sorting the imports?

2017-05-10 19:33 UTC, djbe commented on Tests/Expected/Storyboards-iOS/default-context-all-customname.swift
> +// swiftlint:disable sorted_imports
We can't do that yet from stencil I think?

2017-05-10 19:34 UTC, djbe commented on Tests/Expected/Storyboards-iOS/default-context-all-customname.swift
> +// swiftlint:disable sorted_imports
And even if we could, we'd need to add the imports UIKit or Cocoa to that list, and only then sort it.

2017-05-10 19:36 UTC, Liquidsoul commented on Tests/Expected/Storyboards-iOS/default-context-all-customname.swift
> +// swiftlint:disable sorted_imports
Oups sorry my bad, I was deep in the review and did not see it was a 'expected' file 😅

2017-05-10 19:43 UTC, Liquidsoul commented
LGTM
I'll wait for your change for the rules on one line to check them.
If you want some help on that do not hesitate to tell me, I'd be happy to help 😉

2017-05-11 06:02 UTC, Liquidsoul approved these changes

2017-05-11 08:08 UTC, djbe commented
(accidentally tagged this as breaking, it isn't)

2017-05-11 17:41 UTC, merged