Fonts refactor to use constants
SwiftGen/templates pull request #58
Opened 2017-06-06 12:43 UTC by djbe

Refactored the generated code to use `static let` constants instead of cases, as there is no real use case to want to enumerate over a font name.

There were also some issues with the font registration mechanism, which was broken if:
- the font file had a different name than the font name
- a different extension than "ttf" or "otf"

The fonts were also always re-registered if the font name was different from the font family name. We now directly use the path we receive from the parser, and match using the font family name from the parser.

2017-06-06 12:44 UTC, djbe commented
Note that the branch name has "breaking" in it, but the refactored code turns out to be compatible, so yay! 🎉

2017-06-14 20:35 UTC, Liquidsoul commented
I may see one use case where you would want to iterate over the fonts:
- register the fonts ahead of time (e.g. at App startup)

I've done this by adding a `static let all: [TheFont]` in the enums and then do a `all.forEach().register()`.

2017-06-14 20:41 UTC, Liquidsoul requested changes

2017-06-14 20:41 UTC, Liquidsoul commented on Documentation/fonts/swift2.md
>    enum SFNSDisplay: String, FontConvertible {
The `String, FontConvertible` conformance has been removed in your stencils.

2017-06-14 21:21 UTC, Liquidsoul commented
I've made a [gist](https://gist.github.com/Liquidsoul/c094646b3a7975a6397f707c49a1304d) with a enum version with your fixes and the `all` option on each family name.

2017-06-14 21:24 UTC, djbe commented
Hmm, my original point still stands, there's no reason to enumerate over the fonts, because you can't convert a string to the correct font (using `rawValue`) unless you already know which font family you're targeting.

That doesn't mean we can't add a `all` static constant for those that might want it.

2017-06-15 21:11 UTC, Liquidsoul commented
Ok that's fine by me. We just need to remove the `: String, FontConvertible` part in the markdown files then 😄

2017-07-07 18:15 UTC, AliSoftware commented
@LiquidSoul does my last commit fix your questions? If so could you approve the PR so we can merge? Thx :wink:

2017-07-07 21:33 UTC, Liquidsoul approved these changes

2017-07-07 21:34 UTC, Liquidsoul commented
@AliSoftware LGTM 👍

2017-07-07 21:35 UTC, merged